[package]
name = "taskfi-tlsn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
config = "0.14.0"
serde = "1.0.203"
tlsn-prover = { path = "./dev/tlsn/tlsn-prover" }
