version: "3.8"

services:
  taskfi-tlsn:
    image: taskfi-tlsn/taskfi-tlsn
    build: .
    environment:
      - APP_ENV=production
      - RUST_LOG=warn
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config

  notary:
    image: ghcr.io/tlsnotary/tlsn/notary-server:v0.1.0-alpha.5
    ports:
      - "7047:7047"
    volumes:
      - ./config:/root/.notary-server/config
