name: Rust General CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  lint:
    name: Check lint and format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install necessary tools from Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Run format check
        run: cargo fmt --check

      # - name: Run lint check
      #   run: cargo clippy -- -D warnings
